options:
  dcf_path: "../config"

master:
  node_id: 50
  sync_period: 1000

defaults:
  dcf: "zeroerr.eds"
  sdo:
    - { index: 0x6081, sub_index: 0, value: 0 }
    - { index: 0x6040, sub_index: 0, value: 6 }
    - { index: 0x6060, sub_index: 0, value: 10 }
    - { index: 0x6081, sub_index: 0, value: 4294967295 }
    - { index: 0x6083, sub_index: 0, value: 4294967295 }
    - { index: 0x6084, sub_index: 0, value: 4294967295 }
    - { index: 0x1005, sub_index: 0, value: 128 }
    - { index: 0x1006, sub_index: 0, value: 1000 }
  tpdo:
    1:
      enabled: true
      cob_id: auto
      transmission: 0x01
      mapping:
        - { index: 0x6064, sub_index: 0x00 }
        - { index: 0x606c, sub_index: 0x00 }
    2:
      enabled: true
      cob_id: auto
      transmission: 0x01
      mapping:
        - { index: 0x6077, sub_index: 0x00 }
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - { index: 0x6071, sub_index: 0 }

nodes:
  motor_1:
    node_id: 1
  motor_2:
    node_id: 2
  motor_3:
    node_id: 3
  motor_4:
    node_id: 4
  motor_5:
    node_id: 5
  motor_6:
    node_id: 6
  motor_7:
    node_id: 7
  motor_8:
    node_id: 8
  motor_9:
    node_id: 9
  motor_10:
    node_id: 10
  motor_11:
    node_id: 11

buses:
  robot_can0:
    - { node_id: 7, global_id: 1, encoder: 524288, offset: 262143, reverse: false }
    - { node_id: 8, global_id: 2, encoder: 524288, offset: 262143, reverse: true }
  robot_can1:
    - { node_id: 1, global_id: 5, encoder: 524288, offset: 262143, reverse: false }
    - { node_id: 6, global_id: 0, encoder: 524288, offset: 262143, reverse: false }
  robot_can2:
    - { node_id: 3, global_id: 7, encoder: 524288, offset: 262143, reverse: false }
  robot_can3:
    - { node_id: 2, global_id: 6, encoder: 524288, offset: 262143, reverse: false }
    - { node_id: 11, global_id: 10, encoder: 524288, offset: 262143, reverse: false }
  robot_can4:
    - { node_id: 4, global_id: 8, encoder: 524288, offset: 262143, reverse: false }
    - { node_id: 5, global_id: 9, encoder: 524288, offset: 262143, reverse: false }
  robot_can5:
    - { node_id: 9, global_id: 3, encoder: 524288, offset: 262143, reverse: true }
    - { node_id: 10, global_id: 4, encoder: 524288, offset: 262143, reverse: false }

transforms:
  camera_odometry_to_odometry:
    rpy: [1.57, 0.0, -1.57]
    xyz: [0.077, 0.00922, 1.0]
  camera_to_base_link:
    rpy: [1.57, 0.0, -1.57]
    xyz: [0.077, 0.00922, 0.0]
